// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmjCBUpttYGlq51ye353rUDymL3JuNUhw',
    appId: '1:886352270940:android:9d5694a2c8128f66c47899',
    messagingSenderId: '886352270940',
    projectId: 'presensi-staff-ic',
    storageBucket: 'presensi-staff-ic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVfsh5QQMYZLYk51MJY1Zd2CGTiApNHmQ',
    appId: '1:886352270940:ios:e384b8a77e688b6bc47899',
    messagingSenderId: '886352270940',
    projectId: 'presensi-staff-ic',
    storageBucket: 'presensi-staff-ic.appspot.com',
    iosClientId: '886352270940-1c6cb9oco634pd6u2cau9brhnmv400si.apps.googleusercontent.com',
    iosBundleId: 'com.ic.prensesistaffindonesiacollege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVfsh5QQMYZLYk51MJY1Zd2CGTiApNHmQ',
    appId: '1:886352270940:ios:dbfed4f62007c754c47899',
    messagingSenderId: '886352270940',
    projectId: 'presensi-staff-ic',
    storageBucket: 'presensi-staff-ic.appspot.com',
    iosClientId: '886352270940-bu3iscc384ku3fita6hiakf8dk4imiel.apps.googleusercontent.com',
    iosBundleId: 'com.ic.presensiStaffIc',
  );
}
